### ISSUE TITLE
SAPA requesting vehicles back

### ISSUE THREAD

**Issue by tut001** [saesrpg/saesrpg-group#1]
hey, we have lost some vehicles a while ago and are requesting to have them back. 

here we would like 2 Police-LV's parked for instructor and hq classes with nitro
https://cdn.discordapp.com/attachments/308956559201796097/607885399838425104/mta-screen_2019-08-05_12-36-15.png

here we would like 1 Police-LV parked for cadets with nitro in full white
https://cdn.discordapp.com/attachments/308956559201796097/607885393097916416/mta-screen_2019-08-05_12-36-05.png

we would like to change this FBI Rancher to Police Ranger in full black with nitro, locked to instructor and hq class
https://cdn.discordapp.com/attachments/308956559201796097/607885398567551014/mta-screen_2019-08-05_12-36-48.png

**Comment by IEDaryl** [comment]
Have added Police LV's in white to the garages locked to just Cadet (Bare in mind these garages dont seem to be able to be opened by Cadet, is this something you'd like changed?)

I have added 2 police LV's standard colour and locked to HQ and Instructor. 

I have replaced the FBI Rancher with a Police Ranger locked to HQ and Instructor

Anything else please open another issue or add it to your existing issue topic with all the other SAPA changes))
