### ISSUE TITLE
Cunning Stunts Spawn Changes & Some Things needed 

### ISSUE THREAD

**Issue by Garcia1999** [saesrpg/saesrpg-group#10]
Hello there,
We would like to remove our public/helper spawn in FC>Civ>CS Drifter and wanna add Rookie spawn for probationary members instead of it. 

Spawn code
https://pastebin.com/AeS4w54F

Skin shader

Spawn name: Cunning Stunts Rookie
Skin name: wmydrug
Skin id: 29
Model: https://www.mediafire.com/view/n5f1jwdfi9yydze/csskin.png/file

Also we would like to get ATM at the base and Mech ability 
& Some weapons if possible since we are illegal racers so we need to defend ourselves, we are ok with smg weapon and parachute ( parachute needed for stunts with plane )

**Comment by IEDaryl** [comment]
What's done is done and what is not yet done has been discussed on discord, resolving.
