### ISSUE TITLE
Homeland Security (HLS)

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-group#100]
Hello there, we would like to request 5 moded Patriots added to our Base.

-As fast as DE's Patriots, the same modifications (handling/hight/acceleration).

-Painted fully black.

Thanks in advance.

**Comment by SAES-Jay** [comment]
Will require a Developer or HQ to apply these modifications in-game. We have a large list of names to pick from which starts at Scorpyo and ends there too.
