### ISSUE TITLE
San Andreas Interceptors; Exterior Interior and Spawn update

### ISSUE THREAD

**Issue by bas260** [saesrpg/saesrpg-group#104]
Hello,

I'd like to request the following changes be added to the server. 

Everything was changed from the class names to spawn names and base access. This does mean all the vehicles will have to be re-done. We made the choice to change spawn names because of the spawn names not fitting the ranks we have. We have been using Trooper, Sergeant, Lieutenant etc. for multiple years now. 

I'd also like to have coord added to the spawns. And potlight for all the spawns. 
sai-sgt, sai-cpt and sai-com

The donation vehicles in our base also have to be moved because the parking lot they are currently parked in will not exist in the new mapping. I have around 12 donations vehicles in SAI base SAES>Henry has a 1. 

We have also removed the gas station from our base mapping so that will have to be removed from whatever script is used for refuelling.  

And we would like to have shader on the swat skin changed

> https://i.imgur.com/0OgvNaH.png

All the other links regarding the base;
We have locally tested it ourselves before posting it here. 

> - Spawn Codes: https://pastebin.com/VPXzF0Hj
> - Exterior Mapping: https://mega.nz/file/4WoDiKhZ#EX9k0UzJcf_g0UyTe_Uyr-1EYPFrGVNfp4EeE5XxNKw
> - Interior Mapping: https://mega.nz/file/dXIFGSxC#y4dZOH1-p2A3J6ITtnpTxr-OXzb57RC_Mmlhf2yzOh8
> - SAI Gate codess: https://pastebin.com/Ws6JhR1B
> - SAI Interior gates : https://pastebin.com/eAs3CDz5
> - SAI Shaders: https://cdn.discordapp.com/attachments/716518986761895976/724407674149666936/shaders.rar

I hope I have provided you with the necessary information. If not please contact me.
Thank you in advance for taking the time to handle this request.

Regards,

Bas

**Comment by IEDaryl** [comment]
Rejected, open pending review.

As explained on discord, incorrect format on interior and exterior files, skin shader is 3x allowed size.

**Comment by bas260** [comment]
Spawn Codes: https://pastebin.com/VPXzF0Hj
Base (Interior Exterior & Shaders): https://mega.nz/folder/GzghgAbR#JuRmmC9rMp816NXRXrqPWg
["imagesdds/SAIsign.dds"]={"des_sheriffsign",},
["imagesdds/SAIbillboard.dds"]={"semi3dirty",},
