### ISSUE TITLE
Cluck FM replacement with Q-Dance

### ISSUE THREAD

**Issue by turbo06** [saesrpg/saesrpg-group#107]
Since the closure of the group **Cluck FM** it may get removed and get replaced with 
https://www.jonas13362.com/qdance.m3u : Q-Dance SAES  _(With the permission of Jonas)_

Our topic : https://saesrpg.uk/topic/20478/q-dance-saes-parties-festivals-and-more/2

Our discord: https://discord.gg/a5kxkYd

**Comment by IEDaryl** [comment]
Request rejected, group rewards are not something you can swap out with something else.
