### ISSUE TITLE
Lounge VC - Spawn Request

### ISSUE THREAD

**Issue by AkyZ-collab** [saesrpg/saesrpg-group#110]
Hello,

hereby, with this topic Lounge VC would like to request their spawns:

https://pastebin.com/RurYwdp4 or the downloadable text file in the attachments.

[LoungeVC Spawn.txt](https://github.com/saesrpg/saesrpg-group/files/5048510/LoungeVC.Spawn.txt)

**Comment by faredge00** [comment]
Hello once again,

We have applied some changes to the colors,

https://pastebin.com/WjYF0uVK or the downloadable text file in the attachments.

[Spawn.txt](https://github.com/saesrpg/saesrpg-group/files/5057026/Spawn.txt)

**Comment by AkyZ-collab** [comment]
Closing this as spawn is live.
