### ISSUE TITLE
Homeland Security- Spawn updates.

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-group#118]
Following our conversation, we would like to update our spawns with the following request:

- Replacing the Parachute (ID:46) with Nightvision (ID: 44) for both Tactical Response Unit (TRU) & HLS Director spawns.

- Adding/updating the skins with the following spawns:

 HLS General Agent: 166,165,150.

 HLS Intelligence Unit: 186,141,147.

 HLS Undercover Unit: 240,148,185.

 HLS Tactical Respones Unit: 311,163,164.

Thanks in advance.

**Comment by IEDaryl** [comment]
Weapons update on GM server, Skin update needs to be in the correct format, IE in a spawn code format.

**Comment by DenisIldis** [comment]
Spawn codes (Updated with the new skins): https://pastebin.com/AyuMemZx
