### ISSUE TITLE
SS vehicle changes

### ISSUE THREAD

**Issue by WeppoW** [saesrpg/saesrpg-group#128]
SS shader change to: https://github.com/saesrpg/donation-vehicle-shaders/issues/397

Multiple vehicles which include;
* Stratum(s) police variant
* Newsvan(s) in different models (satelite and police with side bar)
* Cheetah(s) police variant
* Huntley(s) police variant
* Infernus(us) police variant
* Bullet(s) police variant

**Comment by SAES-Jay** [comment]
These are all fine to be added/replaced with the new variants. I will see that the shader is pushed and I will find the time to do the vehicles in-game soon.

Any other queries contact us on the Discord.

:)
