### ISSUE TITLE
SAP Sailors skin shaders 

### ISSUE THREAD

**Issue by Cappo91** [saesrpg/saesrpg-group#13]
Hello, we'd like to have the following examples as the two skin shaders for the SAP Sailors. 

https://cdn.discordapp.com/attachments/608310035713622038/609035828059963402/SAP1.dds
https://cdn.discordapp.com/attachments/608310035713622038/609035806123753482/SAP2.dds

**Comment by IEDaryl** [comment]
SAP2 Uploaded, SAP1 is far too big, please re-request within guidelines.
