### ISSUE TITLE
Outbreak Group rewards

### ISSUE THREAD

**Issue by Ahren7413** [saesrpg/saesrpg-group#14]
As discussed with the Group Management team, we'd like to request the following:

For outbreak-member spawn the following change to their ammo:
`Bat - 1 (No changes)
Deagle - 150 (Increased by 50)
Combat Shotgun - 300 (Increased by 100)
Tec-9 - 250 (No changes)
AK-47 - 350 (Increased by 100)
Sniper - 150 (Increased by 50)
Grenade- 20 (Increased by 10)
Parachute - 1 (No changes)`

For outbreak-dist and outbreak-hq spawn the following change to their ammo:

`Bat - 1 (No changes)
Deagle - 200 (Increased by 100)
Combat Shotgun - 400 (Increased by 200)
Tec-9 - 250 (No changes)
AK-47 - 400 (Increased by 150)
Sniper - 200 (Increased by 100)
Grenade- 20 (Increased by 10)
Parachute - 1 (No changes)`

We've pointed how much ammo we'd like to increase regarding every weapon for each spawn.

Also, as last we'd like the addition to the /selldrug ability to every OB spawn, be it outbreak-member , outbreak-dist and outbreak-hq

Thanks in advance!

**Comment by erentekingunduz** [comment]
noob licano
To make it easier, here's the new spawn code considering the updates above.
https://pastebin.com/8fvhHQzx

**Comment by IEDaryl** [comment]
Assigning Jay to this, will have the agreed upon weapons live by next push.

**Comment by SAES-Jay** [comment]
Will be pushed on the next live update, however I'll assign it to Kain as he'll need to give both Distinctive and HQ spawns the ability to wield dual colts.

Will also need the ability to sell drugs on all spawns.

**Comment by IEDaryl** [comment]
WIll be pushed live on next update, closing.
