### ISSUE TITLE
SAP /group bug 

### ISSUE THREAD

**Issue by Cappo91** [saesrpg/saesrpg-group#15]
Hello, I already explained it in Discord, but I wouldn't mind explaining it again. 

So, SAP's group panel is some kind of merged with SAPA's group panel. No, SAPA member cannot spawn as SAP, they can't see `/groupsay sap`, they are practcially not members of the group, though they're listed down in /group. I've tried to remove any of them, yet nothing happens. 

Here's a screenshot of the /group panel. 
http://prntscr.com/oqwb2q

**Comment by IEDaryl** [comment]
Problem originate from /group reading partial SQL groups as well as the exact SQL groups. 

Bob looking into a fix on the script front - if not possible will rename existing SAP SQL groups to something non-conflicting.

This issue may take slightly longer to resolve than normal.
