### ISSUE TITLE
Group request [RadioSA]

### ISSUE THREAD

**Issue by pothead74** [saesrpg/saesrpg-group#16]
As talked with Group Managers,

Our interior and map shaders got removed somehow, probably mapping needs a restart.

We are also requesting the ability to place/set a radio speaker with (/createradio) and the DFT attached speakers for both regular and hq spawns.

// sql groups are ; radiosa-member and radiosa-hq

**Comment by IEDaryl** [comment]
Your mapping was never uploaded, so that issue should now be fixed.

Looking into the request around /createradio - will get back to you.
