### ISSUE TITLE
Cluckin' Bell Request (/callcluck)

### ISSUE THREAD

**Issue by Tapikillforit** [saesrpg/saesrpg-group#17]
**Hello there,** 

We would like to have a command like /mech for Cluckin' Bell but instead of /mech we would like to call it /callcluck 

**And the alert message which the cluckin' bell member get be like:**

*ALERT*  "CustomersName" Has called in. <CustomersName> is approximately <0000Meters> <south/east/north/west> from you.

**And the message the customer gets when he uses /callcluck:** 

*INFO* Your message has been sent, Cluckin' Bell service will be near you right away!

**Comment by SAESKain** [comment]
I've added a general /food cmd for all food dealers and an extra /cluck so you guys can feel special too. 

Live next push
