### ISSUE TITLE
LWS Updates

### ISSUE THREAD

**Issue by SAESSam** [saesrpg/saesrpg-group#20]
Please may I request the following be processed for LWS.

This was approved by Kenny October 2018.. Blade said he would make it and never did!!!

Firstly, please may our Trusted and HR member spawns construction panel be updated with the following items detailed here https://saesrpg.uk/topic/3000/lws-construction-panel (PM me if you need access to the forum).

Whilst on the spawns, can we add a seperate spawn for LWS Honorary members that doesn't interfere with the HR spawn which has invite/kick access.

Also, 

Please may an option be added within the host event panel to allow the person using LWS services invincibility like LWS members have for the duration of the event which will be then removed at the end of the event. I note this may need to be logged to prevent abuse, however, those messing around with it will be auto kicked from the group.

As well as the above, please can /sell be a further option to be disabled within the LWS event area.

Thanks in advance.

**Comment by IEDaryl** [comment]
Construction panel update assigned to @SAESKain as needs to be done on support.

**Comment by SAESKain** [comment]
Items need giving short relevant names as you would see them in the construction panel

**Comment by IEDaryl** [comment]
No response, closing.
