### ISSUE TITLE
DE MP Spawn

### ISSUE THREAD

**Issue by CrashSystem** [saesrpg/saesrpg-group#3]
Hello, i would like to request Desert Eagles new spawn.

**<-- SPAWN CODE -->**

Goes in Bone County
```xml
    <spawn id="Military Police" skin="287,16" x="37.1" y="1975.38" z="17.75" rot="90" weapons="23,100;3,1;27,200;29,500;31,1200;34,120;17,30" description="Military Police spawn." r="30" g="130" b="30" restricted="group,militarypolice"/>
```
SQL militarypolice to be created and assigned todehq.

**<-- SKIN SHADER -->**

```lua
    ["Military Police"]={
        [287]={['fileName']='de_mp.dds',['textureName']='SKC_MP_US'},
    },        
```
    
[de_mp.dds](https://mega.nz/#!YRcEBCpT!LC3ZryFvJKzxqO3yLA0wxFiPDU4PbVowL_lLWnETHlk)

**<-- ABILITY -->**
Please give this spawn the regular cop abilities (arrest,K panel,kill arrest, etc ..) (@mega9 )

Thank you

**Comment by IEDaryl** [comment]
For the reason Brophy stated above, this request has been denied.

**Comment by xcmoww** [comment]
Sorry Daryl, I should have informed that this was being discussed already by SAESHQ, and Brophys answer was his first impression, so we're waiting for the discussion and final answer.

**Comment by IEDaryl** [comment]
es no problemo my friend, I assumed it was a closed issue so removed it to tidy up, all fine by me if it's still good to go!

**Comment by SAESKain** [comment]
Closed for now.

Monitoring kill arrest in BRs going forward for a bit.
