### ISSUE TITLE
Cunning Stunts Spawn Changes 

### ISSUE THREAD

**Issue by Garcia1999** [saesrpg/saesrpg-group#30]
<-- **SPAWN CODES** -->

1> Change **CS Rookie** spawn to **CS Racer**

```xml
<spawn id="CS Racer" skin="29" x="-533.16027832031" y="-517.95513916016" z="26.380828857422" rot="90" weapons="0,1;24,50" 
description="Cunning Stunts Racers spawn!" r="255" g="178" b="102" restricted="group,cs-racer" />
```

2> Change **CS Member** spawn to **CS Stunter** ( ban this spawn from participant in race flag )

```xml
<spawn id="CS Stunter" skin="180" x="-533.16027832031" y="-517.95513916016" z="26.380828857422" rot="90" weapons="0,1;46,1" 
description="Cunning Stunts Stunters Spawn!" r="255" g="178" b="102" restricted="group,cs-stunter" />
```
3 > As we have 1 skin in each spawn, we would like to have the 2nd skins for CS HQ Spawn which make us have 4 skins in total :

**Spawn name:** CS HQ
**Skin name:** bmypimp
**Skin id:** 249

- And yeah We would like to allow CS HQ spawn to do raceflag i mean unban them, we got approve by GM Team.

<-- **SKIN SHADERS** -->

```lua
["CS Racer"]={
		[29]={['fileName']='bo7h1-1y3f9.dds',['textureName']='wmydrug'},
```
Download Link : http://www.mediafire.com/file/by89hamuzgsn1c0/bo7h1-1y3f9.dds/file

```lua
["CS Stunter"]={
		[180]={['fileName']='bw16w-uao2h.dds',['textureName']='bmytatt'},
```
Download Link : http://www.mediafire.com/file/3vfs9xpz2l2oand/bw16w-uao2h.dds/file

<-- **CS BILLBOARD** -->

We would like to have a billboard 
Image can be found here : https://imgur.com/a/fKyeRuu

<-- **CARS CHANGES** -->

2 Stunts Plane **Done Already**
2 HQ OP Savanna's for HQ **still needed for the op engine, you can take the engine one from tmh executive savanna**
4 Karts **Done Already**
6 Bikes " FCR 900, Sanchez, NRG, MountainBike, QuadBike, BMX " **Still needed for 1 or 2 more bikes**
6 OP Cars **Theres already 4 and 1 monster we need 1 more op car which is SuperGT OP** 
6 Drift Cars " Hotring Race 3, Sentinel, Jester, Hotring Race 1, Comet, Feltzer " **Still needed for car changes and driftable handle ingame**

**Comment by IEDaryl** [comment]
Invalid request format, feedback given on discord - when updated ping me on discord.

**Comment by Garcia1999** [comment]
Edited, also you can use this as spawn codes if you find any issues
```xml
        <class id="Cunning Stunts" >
            <spawn id="CS Stunter" skin="180" x="-533.16027832031" y="-517.95513916016" z="26.380828857422" rot="90" weapons="0,1;46,1"
            description="Cunning stunts Stunters spawn!" r="255" g="178" b="102" restricted="group,cs-stunter" />
            <spawn id="Cunning Stunts HQ" skin="21" x="-533.16027832031" y="-517.95513916016" z="26.380828857422" rot="90" weapons="0,1;46,1"
            description="Cunning stunts HQ spawn!" r="255" g="178" b="102" restricted="group,cs-hq" />
            <spawn id="CS Racer" skin="29" x="-533.16027832031" y="-517.95513916016" z="26.380828857422" rot="90" weapons="0,1;24,50" 
            description="Cunning Stunts Racers spawn!" r="255" g="178" b="102" restricted="group,cs-racer" />
        </class>
```

**Comment by IEDaryl** [comment]
Live on GM, pushed at some point once gang management pulls the finger out!

Billboard denied, needs to be PNG and 501x158 res
