### ISSUE TITLE
SAM Spawn updates.

### ISSUE THREAD

**Issue by ProNuBs** [saesrpg/saesrpg-group#31]
Hello I've got another request for SAM, 

These include some spawn updates. 

- Rotation to some spawns updated as well as  slightly moving some to have a better spawnpoint (Mainly Air spawns moved to roofs to spawn next to the mavericks)
- Weapons updated to match the spawn (Parachutes for Air, Sea and Chief, Infrared for EMS)
- New shaders

Link to the spawncodes: https://pastebin.com/aY348Yt9
I've Shared the shaders in the SAM Discord Group Management channel (Files are named according to the skin we're using for each spawn)

**Comment by IEDaryl** [comment]
Spawncodes invalid request format, feedback on discord, when updated let me know

**Comment by ProNuBs** [comment]
Should be updated now

**Comment by IEDaryl** [comment]
Shader issue as no texture names given, feedback on discord, waiting on new info.

**Comment by IEDaryl** [comment]
Donezo
