### ISSUE TITLE
Centrino Spawn/shaders updates

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-group#32]
Hello there SAES, we Centrino Management team would like to request our very first shaders as we don't have them yet, each class will count with 1 shader for a total of 3. we're aswell requesting the skin Number 290 for the Management spawn. thanks for your time.

< -- Spawn Codes -- >

 https://pastebin.com/qHK2RimH

1.1 < --- SHADERS --- >

Spawn name: Centrino Management
Skin name: rose
Skin id: 290
Model: https://i.imgur.com/lMheJZX.png

Spawn name: Centrino Logistics
Skin name: bmyap
Skin id: 16
Model:  https://imgur.com/a/SD0iNT5

Spawn name: Centrino Transportation
Skin name: heck2
Skin id: 259
Model: https://imgur.com/a/Uge9yRp

**Comment by IEDaryl** [comment]
Request temporarily declined, skin shaders are too large. Should be under 65kb and in dds file format. (256x512)Please fix.

**Comment by IEDaryl** [comment]
Not updated, closing.
