### ISSUE TITLE
Cunning Stunts - Access to race flags

### ISSUE THREAD

**Issue by Howlze** [saesrpg/saesrpg-group#34]
Hi,

Currently Cunning Stunts do not have access to participate in race flags, even though it is pretty much a group surrounding racing and alike. The Motor Heads (TMH) has full access to race flags, and can participate.

There is an ongoing rule, which states that you may **NOT** use any modified vehicles to participate in race flags - obviously. However, despite this, Cunning Stunts still has not gotten access to the race flags script (Just states, that this class is not able to participate in race flags).

**Comment by Garcia1999** [comment]
Hello, Mr Howzle, i have explained everything in #group-squad-gang-help but am gonna do that again, i was waiting for long time to talk about that and this msg is for GM and everyone else who is a racer, of course theres no point about you, thanks anyways

We as Cunning Stunts did changes and its already on github if you wanted to check it out here is it 
https://github.com/saesrpg/saesrpg-group/issues/30

YesWe have Modded/op cars for CS and we can raceflag with but, 
First we **dont allow** our members to raceflag with op cars, we use it only for stunts, as you know normal cars are not that fast which make you not to stunts, Second, we have been driving with op cars for like almost 5 months and theres no member from CS in the top list of the racers in all the raceflags (which make us not participating with op cars)
Third, lets back on to CS Changes on github i hope everyone gonna read it well, but i'll remind you again that CS HQ spawn are banned from raceflag as you said above and i have been looking for any GM ingame to lock the current op cars for CS HQ only (untill we get the new changes) 



>i have been looking for any GM ingame to lock the op cars for CS HQ only

I am pretty sure that i have asked many admins ingame to lock the cars for cs hq but they said its GM/SAESHQ work. anyways if theres any admin seeing my comment here, do for me a favor and lock the cars with black color to CS HQ only you can find them in parking (right side) 


I appreciate your issue and thanks for the request.



Regards ~ Cunning Stunts HQ
