### ISSUE TITLE
SAP's new Skin shaders. 

### ISSUE THREAD

**Issue by Cappo91** [saesrpg/saesrpg-group#35]
In the name of the SAP HQ, I'm here to request some changes regarding out skins. 

SAP Captain shader - 
https://cdn.discordapp.com/attachments/465393910081126410/634446943073861642/t2.dds

We'd like to have it in the place of the first skin that we have (in the place of this one http://prntscr.com/pl7vl0 )

SAP Sailor shader - 
https://cdn.discordapp.com/attachments/465393910081126410/634446939676737556/t4.dds

We'd like to have it in the place of the second skin that we have. (in the place of this one http://prntscr.com/pl7vy1 )

**Comment by IEDaryl** [comment]
Hey - can you create your request for shaders in the XML format. 

Here is an example of how your current shaders are;

```	["SAP Sailor"]={
		[122]={['fileName']='SAP2.dds',['textureName']='dnb2'},
		},	
	["SAP Sailor"]={
		[108]={['fileName']='SAP1.dds',['textureName']='lsv1'},
		}, ```

**Comment by Cappo91** [comment]
["SAP Sailor"]={
        [174]={['fileName']='SAP2.dds',['textureName']='sfr2'},
        },
    ["SAP Captain"]={
        [175]={['fileName']='SAP1.dds',['textureName']='lsfr3'},
        },



Here it is, we're not completely sure if it's correct (as I was pushy enough to make Jonas do it as he was at work).

**Comment by IEDaryl** [comment]
In the code given you have SAP2.dds and SAP1.dds

You need to change this to match the file names of the skins you're giving as I can't tell which is which. Make sure the correct file name is linked to the correct skin

**Comment by Cappo91** [comment]
I apologize for that! 
I hope this one works. 

["SAP Sailor"]={
[174]={['fileName']='t4.dds',['textureName']='sfr2'},
},
["SAP Captain"]={
[175]={['fileName']='t2.dds',['textureName']='sfr3'},
},

**Comment by IEDaryl** [comment]
Done, live on next push
