### ISSUE TITLE
SAFD ~ Spawn update

### ISSUE THREAD

**Issue by Laza-22** [saesrpg/saesrpg-group#36]
Hello, after a long time we've decided to do some changes with SAFD.

- Our request is changing spawn names and adding one more spawn within SAFD, if that is going to be possible.
- We'd like to add our own shaders on all those skins. 
- To be changed on all spawn locations (San Fierro & Las Venturas & Los Santos & Bone Country).

Link to the spawncodes: https://pastebin.com/wJUTuThT

A quick note: 
- spawn locations are created for LV only, if it's needed to be created for each one, let us know, I hope this is fine.

**Comment by IEDaryl** [comment]
Spawn denied as per discord conversation.

Changing names is fine, you stated you want shaders but didn't upload any?

**Comment by IEDaryl** [comment]
Closing in favour of

https://github.com/saesrpg/saesrpg-group/issues/37
