### ISSUE TITLE
SAFD Changes

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-group#37]
Hello, after a long time we've decided to do some changes within SAFD.

**A quick note:**

Spawn locations are created for Las Venturas only, if it's needed to be created for each one, let us know, I hope this is fine.
But, we'd like to have spawns also in Bone County, Los Santos and San Fierro. (4 different locations).

**Spawn Codes:** https://pastebin.com/FzQJ5cQj
**Spawn Shaders:** Spawn shaders are already in the server, and there are no changes regarding shaders.

**Remove:** Also, please remove SAFD Spawns in Red County, the rest is deleted already (base, vehicles). As we have decided not to have firehouse there anymore. 'Siren icon' on minimap should be removed aswell.

**Comment by Ramos116** [comment]
Bone County Spawns Location: x="-231.83000183105" y="1206.1400146484" z="19.7421875" rot="90"

Los Santos Spawns Location: x="1724.6999511719" y="-1126" z="24.085935592651" rot="90"

San Fierro Spawns Location: x="-1531.4000244141" y="1111.1999511719" z="7.1875" rot="90"

**Comment by IEDaryl** [comment]
Changes are live on GM, will be live on next push.

In future you need to state your shader changes as I've had to do them all manually (change the spawns they're associated to, etc.) so it may not be 100% what you're looking for.
