### ISSUE TITLE
Cunning Stunts Some Changes Needed for the last changes!

### ISSUE THREAD

**Issue by Garcia1999** [saesrpg/saesrpg-group#38]
some changes needed from this changes 
https://github.com/saesrpg/saesrpg-group/issues/30

```First``` 
Wee have a parachute in CS Racer spawn, but we requested a 50 ammo of deagle, not parachute so remove parachute and add deagle 

```Second,```
 CS HQ spawn still banned from raceflag, and CS Stunter one is not, but we requested the opposite @SAESKain is the one and the only who can handle this as i think

```Last```
 vehicles changes of course:

```We have 28 vehicles in total we want to change them and get```

* 2 Stunts Plane [ **Done Already** ] /// lock them all the spawns ' Cunning Stunts ' \\\
* 4 Karts [ **Done Already** ] /// lock them all the spawns ' Cunning Stunts ' \\\
* 4 Bikes [ **Done Already** ] /// lock them all the spawns ' Cunning Stunts ' \\\
* 1 towtruck [ **Done Already** ] /// lock them all the spawns ' Cunning Stunts ' \\\

* 2 OP Savanna's for CS HQ **One is already done we need another one** /// lock them to Cunning Stunts HQ only \\\
* 6 OP Cars [ **Theres already 4 and 1 monster ,we need 1 more op car which is SuperGT OP** ] /// lock them to ' Cunning Stunts HQ ' and ' Cunning Stunts Stunter ' \\\
* 6 Drift Cars [ **Hotring Race 3 / Sentinel / Jester / Hotring Race 1 / Comet / Feltzer** ] (must be drift handle cars) /// lock them to ' Cunning Stunts HQ ' and ' Cunning Stunts Racer ' \\\

***Note:*** *find any cs hq to show location ingame*

```All thats cars changes make us have 25 vehicles in total instead of 28```

***Important : And yeah if possible add also a deagle for CS HQ since we have only parachute in CS HQ spawn and also cs hq spawn have both abilities of the both other spawn, (this is a new request not in the old one in github)***

**Comment by IEDaryl** [comment]
Deagle done -  live on next push, vehicles cannot be done by GM's. 

You need to find a SAES HQ to do this for you when they're in game.

@SAESKain Can you remove CS from raceflag restrictions.
