### ISSUE TITLE
Desert Eagles Military Academy - Shader

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-group#39]
Good Day, Well After quite some time of figuring out what we'd do with the Cadet shade, we've finally come up with it. Size already solved.

Desert Eagles Military Academy

Military Cadet Shader:

http://www.mediafire.com/file/355v59gqlwphtve/Cadet1.dds/file

---

Skin Details:
Skin Number : 16
Model : bmyap

---

```lua
    ['Military Cadet']={
        [16]={['fileName']='Cadet1.dds',['textureName']='bmyap'},
    },
```

**Comment by tut001** [comment]
Use this file instead. In the current state of the shader there's no reason for it to be 105kb higher than gang shaders. 
https://cdn.discordapp.com/attachments/308956559201796097/639207521244020756/Cadet1.dds

**Comment by stayA9** [comment]
Fixed 85kb recheck please

**Comment by tut001** [comment]
No, gang shaders are 64kb at 256x512 and there's absolutely no reason it should go any higher than that. Make sure that you're compressing the image with DXT1 compression without mipmaps.

**Comment by stayA9** [comment]
Edited, thank you.

**Comment by IEDaryl** [comment]
This is donezo, it's on GM and will be live on next push.
