### ISSUE TITLE
Centrino - Spawn Updates / shaders

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-group#40]
Here once again and this time for good, We've fixed all the shaders now here the details

As we have only 1 skin at our current HQ spawn we would like to request the addition of the Skin N° 290 for the Management Spawn, and The Skin N° 16 for the Logistics spawn instead of the one we already have 

Centrino Management: Skin 290 

Removing the Skin N° 161(cwmyfr) from the Logistics spawn to replace for the Skin N° 16 (bmyap)

---

Spawn Codes: https://pastebin.com/qHK2RimH

---

1.1 < --- SHADERS --- >

Spawn name: Centrino Management
Skin name: rose
Skin id: 290
Link: http://www.mediafire.com/file/04ed65zmq4pi5cx/CentrinoMang.dds/file

```lua
    ['Centrino Management']={
        [290]={['fileName']='CentrinoMang.dds',['textureName']='rose'},
    },
```

---

Spawn name: Centrino Logistics
Skin name: bmyap
Skin id: 16
Link: http://www.mediafire.com/file/9kj1cwavpjqnirb/CentrinoLogist.dds/file

```lua
    ['Centrino Logistics']={
        [16]={['fileName']='CentrinoLogist.dds',['textureName']='bmyap'},
    },
```

---

Spawn name: Centrino Transportation
Skin name: heck2
Skin id: 259
Link: http://www.mediafire.com/file/lrghhll84wzp6eb/CentrinoTrans.dds/file

```lua
    ['Centrino Transportation']={
        [259]={['fileName']='CentrinoTrans.dds',['textureName']='heck2'},
    },
```

---

Kind Regards ~ Centrino HQs

**Comment by IEDaryl** [comment]
Donezo, live on GM and will be on live when there is a push
