### ISSUE TITLE
Lightning World Sports Objects Request

### ISSUE THREAD

**Issue by IamYoko** [saesrpg/saesrpg-group#43]
Good afternoon gents,

We would like to have this objects added to the event panel, you will find below the name and ID of the objects we're requesting. Any question feel free to contact me or any other HQ on discord.

Thank you in advance!

Kind regards,

Objects:

1-    China   (ID: 2098)
2-    Sports Wall   (ID: 2395)
3-    Dojo Wall   (ID: 2755)
4-    Bike Log   (ID: 18367)
5-    Car Shade Roof   (ID: 3458)
6-    Club Gate  (ID: 3749)
7-    Stunt 1  (ID: 13647)
8-    Wall 5    (ID: 4724)
9-    Gate 1  (ID: 7033)
10-    Ring   (ID: 3438)
11-    Dome Building   (ID: 3873)
12-    Wall 6  (ID: 7921)
13-    Dome  (ID: 7586)
14-    China Gate  (ID: 9482)
15-    New Fence   (ID: 7191)
16-    Pirate Ship  (ID: 8493)
17-    Tolls  (ID: 9623)
18-    Small hut   (ID: 11426)
19-    Tower Hut  (ID: 11427)
20-    Castle Tower   (ID: 8620)
21-    Parking Garage   (ID: 8947)
22-    Weird Wall  (ID: 11442)
23-    Church Tower  (ID: 8131)
24-    Hut 1  (ID: 11457)
25-    Hut 2  (ID: 11440)
26-    Pillar   (ID: 3494)
27-    Cabin Log  (ID: 18259)
28-    Weird Wall 2  (ID: 11441)
29-    Cell Gate  (ID: 2930)
30-    Jetdoor A51  (ID: 3095)
31-    Hot Statue  (ID: 14467)
32-    Pillar 2   (ID: 3499)
33-    Clown Sign   (ID: 7231)
34-    Steps  (ID: 13644)
35-    Gas Station  (ID: 3187)
36-    Highway Sign   (ID: 3337)
37-    Statue  (ID: 3471)
38-    Burger Shot Sign  (ID: 2643)
39-    Car Bumper Sign  (ID: 10281)
40-    Pillar 3     (ID: 3437)

**Comment by SAESKain** [comment]
Present objects in this format please
     	        ["Large shrub rock"] = {745,0,0,0},
		["Lots of Flowers"] = {869,0,0,0},
		["Tree"] = {618,0,0,0},
		["Helipad 2"]={3934,0,9.9},
Where the first number is the object id

**Comment by IamYoko** [comment]
Good afternoon Kain,

Please check the format below, should work, if not please let me know.

[“Chine”] = {2098,0,0,0},
[“Sports Wall”] = {2395,0,0,0},
[“Dojo Wall”] = {2755,0,0,0},
[“Bike log”] = {18367,0,0,0},
[“Car Shade Roof”] = {3458,0,0,0},
[“Club Gate”] = {3749,0,0,0},
[“Stunt 1”] = {13647,0,0,0},
[“Wall 5”] = {4724,0,0,0},
[“Gate 1”] = {7033,0,0,0},
[“Ring”] = {3438,0,0,0},
[“Dome Building”] = {3873,0,0,0},
[“Wall 6”] = {7921,0,0,0},
[“Dome”] = {7586,0,0,0},
[“China Gate”] = {9482,0,0,0},
[“New Fence”] = {7191,0,0,0},
[“Pirate Ship”] = {8493,0,0,0},
[“Tolls”] = {9623,0,0,0},
[“Small Hut”] = {11426,0,0,0},
[“Tower Hut”] = {11427,0,0,0},
[“Castle Tower”] = {8620,0,0,0},
[“Parking Garage”] = {8947,0,0,0},
[“Weird Wall”] = {11442,0,0,0},
[“Church Tower”] = {8131,0,0,0},
[“Hut 1”] = {11457,0,0,0},
[“Hut 2”] = {11440,0,0,0},
[“Pillar”] = {3494,0,0,0},
[“Cabin Log”] = {18259,0,0,0},
[“Weird Wall 2”] = {11441,0,0,0},
[“Cell Gate”] = {2930,0,0,0},
[“Jetdoor A51”] = {3095,0,0,0},
[“Hot Statue”] = {14467,0,0,0},
[“Pillar 2”] = {3499,0,0,0},
[“Clown Sign”] = {7231,0,0,0},
[“Steps”] = {13644,0,0,0},
[“Gas Station”] = {3187,0,0,0},
[“Highway Sign”] = {3337,0,0,0}, 
[“Statue”] = {3471,0,0,0},
[“Burger Shot Sign”] = {2643,0,0,0},
[“Car Bumper Sign”] = {10281,0,0,0},
[“Pillar 3”] = {3437,0,0,0},

**Comment by SAESKain** [comment]
["Dojo wall"] = {2755,0,0,0},
		["Stunt parcour"] = {13647,0,0,0},
		["Wall 5"] = {4724,0,0,0},
		["Pirate Ship"]={8493,0,26.8},
		["Ruin 3"] = {11442,0,0,0},
		["Ruin 1"] = {11440,0,0,0},
		["Pillar 4"] = {3494,0,0,0},
		["Cell gate"] = {2930,0,0,0},
		["Billboard"] = {3337,0,0,0},
		["Statue 3"] = {3471,0,0,0},
		["Carshop sign"] = {10281,0,0,0},
		["Blue Pillar Light"]={3437,0,15.7},

		["Chine"] = {2098,0,0,0},
		["Sports Wall"] = {2395,0,0,0},
		["Bike log"] = {18367,0,0,0},
		["Car Shade Roof"] = {3458,0,0,0},
		["Club Gate"] = {3749,0,0,0},
		["Gate 1"] = {7033,0,0,0},
		["Ring"] = {3438,0,0,0},
		["Wall 6"] = {7921,0,0,0},
		["China Gate"] = {9482,0,0,0},
		["Ruin 8"] = {11426,0,0,0},
		["Tower Hut"] = {11427,0,0,0},
		["Square Garage"] = {8947,0,0,0},
		["Ruin 9"] = {11457,0,0,0},
		["Cabin Log"] = {18259,0,0,0},
		["Ruin Wall"] = {11441,0,0,0},
		["Jetdoor A51"] = {3095,0,0,0},
		["Hot Statue"] = {14467,0,0,0},
		["Pillar 2"] = {3499,0,0,0},
		["Steps"] = {13644,0,0,0},

These items were approved, some have been removed due to not having collisions or just being bad
