### ISSUE TITLE
Several IAC Changes

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-group#44]
Hello on behalf of the IAC HQ we would like to request the following things:
 
**BASE EXTERIOR MAPPING:**
[Available here](http://www.mediafire.com/file/sr7bll26rz6jq6e/IAC_1.lua/file)
 
**BASE INTERIOR MAPPING**
[Available here](http://www.mediafire.com/file/qj1y28k9tdrx5bv/iac-int_1.lua/file)
 
**GATES**
`<trigger x="1859.6999511719" y="129.5" z="37.799999237061" height="4.0" radius="8" movetime="2000" allowed="team,IAC Dispatcher,IAC Administration,IAC Unit">
    <gate object="980" pos="1860.3000488281,129.30000305176,40.799999237061,0,0,270" start="1860.3000488281,129.30000305176,40.799999237061,0,0,0" finish="1861.1999511719,129.30000305176,45.5,0,0,0" />
</trigger>`
 
**MARKERS**
`<interior  name="IAC">
<entry pos="1903.90613,135.24306,41.05854" rotation="90" int="0" dim="0" />
<exit pos="1911.87720,136.11382,68.78344" rotation="180" int="0" dim="0" />
</interior>`
 
`<interior  name="IAC2">
<entry pos="1907.76270,140.53796,68.7834" rotation="90" int="0" dim="0" />
<exit pos="1910.76270,140.53796,419.21268" rotation="180" int="0" dim="0" />
</interior>`
 
`<interior>
<entry pos="1903.9000244141,108.59999847412,42.400001525879" rotation="270" int="0" dim="0" />
    <exit pos="227.69999694824,1872.4000244141,14.300000190735" rotation="90" int="0" dim="177" />
</interior>`
 
**SPAWN CODE**
`<class id="InvestArms Corporation">
            <spawn id="IAC Dispatcher" skin="164" x="1892" y="147.39999389648" z="41.099998474121" rot="200.000915" weapons="24,120;29,250;31,350;46,1;34,150"
            description="IAC Dispatcher" r="173" g="227" b="255" restricted="group,iac-dispatcher" />`
 
`<class id="InvestArms Corporation">
            <spawn id="IAC Administration" skin="164" x="1892" y="147.39999389648" z="41.099998474121" rot="200.000915" weapons="24,120;29,250;31,350;46,1;34,150"
            description="IAC Administration" r="173" g="227" b="255" restricted="group,iac-administration" />`
 
`<class id="InvestArms Corporation">
            <spawn id="IAC Unit" skin="164" x="1892" y="147.39999389648" z="41.099998474121" rot="200.000915" weapons="24,120;29,250;31,350;46,1;34,150"
            description="IAC Unit" r="173" g="227" b="255" restricted="group,iac-unit" />`
 
We would like to add sell weapons ability on IAC Unit
 
**SKIN SHADERS**
WYMBOUN
http://www.mediafire.com/file/795jayoi98h0wx0/bo4ny-m7wqw.dds/file
SWAT
http://www.mediafire.com/file/i1xhuttl60zd83w/b33qh-njlvc.dds/file
 
**ATM COORDINATES**
`1904.4000244141,105.40000152588,40.700000762939,270`

Also, Would you add admin permissions for Paradox
Link to his profile: https://saesrpg.uk/user/paradox

**Comment by IEDaryl** [comment]
Request denied, map files are completely broken and do not load any objects.

please review
