### ISSUE TITLE
Radio SA changes/requests

### ISSUE THREAD

**Issue by pothead74** [saesrpg/saesrpg-group#46]
Regarding the DJ truck : 

```xml
  streamMaxDistance = 200
  streamMinDistance = 50
  streamVolume = 1.0

---
setVehiclePlateText(vehicle, "RadioSA")

```

Also we'd like to give the regular spawn the access to drive the truck(spawning it remains to hq spawn only).

And as talked to GMs, we want our blip to be shown on the map for everyone.

cheers.

**Comment by IEDaryl** [comment]
Changes should have been done & put live, lmk if any issues.
