### ISSUE TITLE
IAC Changes 

### ISSUE THREAD

**Issue by Kim01900** [saesrpg/saesrpg-group#47]
Hello on behalf of the IAC HQ we would like to request the following things:
***
BASE EXTERIOR MAPPING:
[Available here](https://www.mediafire.com/file/vx124uefp0qwoi5/ia-base.zip/file)

#main gate

`<trigger x="1942.400390625" y="137.900390625" z="38.900001525879" height="4.0" radius="8" movetime="2000" allowed="class,InvestArms Corporation,IAC Dispatcher,IAC Administration,IAC Unit">`
   ` <gate object="971" pos=" 1942.400390625,137.900390625,41.900001525879,0,0,343.99291992188" start=" 1942.400390625,137.900390625,41.900001525879,0,0,343.99291992188" finish=" 1942.400390625,137.900390625,35.099998474121,0,0,343.99291992188" />
</trigger>`

#lab gate

`<trigger x="1905.599609375" y="155.2001953125" z="38.700000762939" height="4.0" radius="4" movetime="4000" allowed="class,InvestArms Corporation,IAC Dispatcher,IAC Administration,IAC Unit">`
   ` <gate object="2963" pos=" 1905.599609375,155.2001953125,38.700000762939,0,0,252.49877929688" start=" 1905.599609375,155.2001953125,38.700000762939,0,0,252.49877929688" finish=" 1908.8000488281,154.19999694824,38.700000762939,0,0,252.49877929688" />
</trigger>`

#garage gate

`<trigger x="1930.1999511719" y="163.19999694824" z="37.599998474121" height="4.0" radius="8" movetime="4000" allowed="class,InvestArms Corporation,IAC Dispatcher,IAC Administration,IAC Unit">`
   ` <gate object="8948" pos=" 1930.2001953125,163.2001953125,39.200000762939,0,0,343.99291992188" start=" 1930.2001953125,163.2001953125,39.200000762939,0,0,343.99291992188" finish=" 1927.3000488281,164,42.299999237061,0,270,343.99291992188" />
</trigger>`

#entrance gate

`<trigger x="1874.6999511719" y="63.099998474121" z="35.700000762939" height="4.0" radius="8" movetime="2000" allowed="class,InvestArms Corporation,IAC Dispatcher,IAC Administration,IAC Unit">`
   ` <gate object="2920" pos=" 1873.5,65.900390625,35.700000762939,90,0,22.999877929688" start=" 1873.5,65.900390625,35.700000762939,90,0,22.999877929688" finish=" 1873.5,65.900390625,35.700000762939,0,0,22.999877929688" />
</trigger>`

#para warp

`<interior restriction="class,InvestArms Corporation,IAC Dispatcher,IAC Administration,IAC Unit" name="IACPara">
    <entry pos="1912.0999755859,169.69999694824,44.599998474121" rotation="90" int="0" dim="0" />`
    `<exit pos="1916.5999755859,172.80000305176,600" rotation="90" int="0" dim="0" />
</interior>`

#spawn

`<class id="InvestArms Corporation"> <spawn id="IAC Dispatcher" skin="164" x="1933.0999755859" y="148.80000305176" z="38.5" rot="260.003662" weapons="24,120;29,250;31,350;46,1;34,150" description="IAC Dispatcher" r="173" g="227" b="255" restricted="group,iac-dispatcher" />`

`<class id="InvestArms Corporation"> <spawn id="IAC Dispatcher" skin="164" x="1933.0999755859" y="148.80000305176" z="38.5" rot="260.003662" weapons="24,120;29,250;31,350;46,1;34,150" description="IAC Administration" r="173" g="227" b="255" restricted="group,iac-administration" />`

`<class id="InvestArms Corporation"> <spawn id="IAC Dispatcher" skin="164" x="1933.0999755859" y="148.80000305176" z="38.5" rot="260.003662" weapons="24,120;29,250;31,350;46,1;34,150" description="IAC Unit" r="173" g="227" b="255" restricted="group,iac-unit" />`

SKIN SHADERS:
["IAC Dispatcher"]={
[174]={['fileName']='WMYBOUN.dds',['textureName']='wmyboun'},
},
["IAC Unit"]={
[175]={['fileName']='swat.dds',['textureName']='swat'},
},

WMYBOUN
http://www.mediafire.com/file/7f4hq4av9y3g4om/WMYBOUN.dds/file
SWAT
http://www.mediafire.com/file/53n7do3qud0pppb/swat.dds/file
***
Also we would like to request sell weapons ability on IAC Unit.
Also, Would you add admin permissions for Paradox
Link to his profile: https://saesrpg.uk/user/paradox

**Comment by IEDaryl** [comment]
Rejected based on size of shaders, feedback given on discord - re-request when ready.
