### ISSUE TITLE
IAC's new base request

### ISSUE THREAD

**Issue by Lincolnthc** [saesrpg/saesrpg-group#5]
With the permission of IAC HQ, I am here to request our new base. You will be able to find everything you need in the following files. Any issues regarding this, you can contact either me or Karma on discord. Discord ID : Karma#3391.

[IAC_base_2.zip](https://github.com/saesrpg/saesrpg-gang/files/3288235/IAC_base_2.zip)

Interiors : https://pastebin.com/7hsLhkSR
Gates : https://pastebin.com/hhxVZRnE

**Comment by IEDaryl** [comment]
I'm not keen on keeping antiquated issues so I will close this, please re-open the issue when you have corrected the mapping.

As discussed on the next push to live your spawn will be moved to LV. Will implement mapping ocne it's done.
