### ISSUE TITLE
SAFD - Changing coords, weapons

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-group#52]
Hello, we have requested spawn changes somewhere in October. Some of the changes were not done correctly, and few are missing.

**Please set those coords for the spawns placed in San Fierro:**

San Fierro Spawns Location: x="-1531.4000244141" y="1111.1999511719" z="7.1875" rot="90"

**About weapons:**

- I have made spawn codes and stated what weapons we should carry, and unfortunately, 'Cane' and 'Infrared' were not added to the spawns, so I'm requesting them once again to be added.

Item 'Cane' ( 15, 0 ) should be added to 'SAFD-full', 'SAFD-c', SAFD-lt', 'SAFD-dc'.
Item 'Infrared' ( 45, 0 ) should be added to 'SAFD', 'SAFD-full', 'SAFD-c', SAFD-lt', 'SAFD-dc'.

Instead of writting here what is missing, this is a spawn code link to checkout how we requested before: https://pastebin.com/FzQJ5cQj

**Comment by IEDaryl** [comment]
Live on next update
