### ISSUE TITLE
TMH additional skin request

### ISSUE THREAD

**Issue by taj125** [saesrpg/saesrpg-group#61]
Hello there! 
Since a long time, TMH has been approved for another skin by the GM team, a female one in fact, with shaders. That makes us have total of 4 shaders. And so finally after having dealt with many comflicts inside the team, I'm here to request it.

This skin (ID is 193) -> https://cdn.discordapp.com/attachments/384447237754978304/655471160678416424/11111111.dds

We'd like to have it as a secondary skin for **all** of our spawns (namely - TMH Executive, TMH Technical and TMH Racer). For any queries, I can be personally contacted on discord almost all the time. Thanks in advance! and Happy new year!

**Comment by IEDaryl** [comment]
Live next push!
