### ISSUE TITLE
Outbreak Organization New Base

### ISSUE THREAD

**Issue by erentekingunduz** [saesrpg/saesrpg-group#62]
### **Hello dear Group Managers,**

We, as the Outbreak Organization, would like to request a new base and of course new gates, markers, base shaders and spawn code for our group. The property we have got the mapping on belongs to Joe and we have his approval to use his property.

### **Base Files:**
**Mapping** -> Check the second post please.
**Mapping Shaders** -> Check the second post please.
**Shaders Script** -> Check the second post please.

### **Spawns:**
**Spawn Code** -> https://pastebin.com/PMMbgkaV
_Skin shaders and spawn names are not changed, so it's not needed to change the shaders and their script._

### **Gates/Markers:**
**Gates** -> Check the second post please.
**Markers** -> https://pastebin.com/LQcWvt6e

### **Vehicles:**
We would like to sort them out ingame.

If anything is missing or broken, please let us know.
Thanks in advance.
Outbreak HQ Team.

**Comment by erentekingunduz** [comment]
**Base mapping:** https://pastebin.com/zRxxhc6f
**Gates:** https://pastebin.com/aX0e2FQX
**Shaders (dds):** https://www.dropbox.com/s/ofck29l095wysrd/OBShaderdsDDS.rar?dl=0
**Shaders script:** https://pastebin.com/ShCs23uf

**Comment by IEDaryl** [comment]
All done, live on next merged & push
