### ISSUE TITLE
SAP spawns changes

### ISSUE THREAD

**Issue by Cappo66** [saesrpg/saesrpg-group#67]
Hi, in the name of the SAP HQ, I'd like to request a change of the amount and the type of guns that both of our spawns have, as well as renaming the SAP Sailor spawn to SAP Raider.

https://pastebin.com/376xjeWF
Plus katana for both spawns, the ID of the katana is 8, but I was unsure how exactly I should write it in the things above, so I'm stating it here.

So, here are the weapon changes:

SAP Raider:
Katana
130 sniper bullets
300 m4 bullets
120 uzi bullets
10 grenades 
130 CS bullets
100 deagle bullets 

SAP Captain: 
Katana
130 sniper bullets
300 ak47 bullets
120 tec bullets
10 grenades 
100 sawed off bullets
100 deagle bullets

**Comment by Cappo66** [comment]
SPAWN #1

<spawn id="SAP Raider" skin="108,174" x="-1477.36597" y="-2943.65601" z="2.75469" rot="90" weapons="24,100;27,150;28,150;31,350;34,150;16,10" description="The Raider of SAP" r="1" g="81" b="80" restricted="group,sap"/>

SPAWN #2

<spawn id="SAP Captain" skin="33,175" x="-1495.19165" y="-2939.92261" z="3.01499" rot="90" weapons="24,100;27,150;28,150;31,350;34,150;16,10"  description="The Captain of SAP, " r="1" g="81" b="80" restricted="group,sap-captain"/>

**Comment by iMatizZ** [comment]
The last version is wrong so here is correct one : https://pastebin.com/376xjeWF

**Comment by IEDaryl** [comment]
Live next push!
