### ISSUE TITLE
Desert Eagles | Spawn changes

### ISSUE THREAD

**Issue by ghost** [saesrpg/saesrpg-group#69]
Dear Group Management,

I'm requesting spawn changes for DE to accommodate for some changes we're trying to work out in the group. First, we would like to remove a spawn, the spawn we want to be removed is:
Bone County -> Desert Eagles -> **Military Cadet**

---

For the changes we want the following spawn to be renamed:
**From:** Bone Country -> Desert Eagles -> **Recruit**
**To:** Bone County -> Desert Eagles -> **Military Recruit**

&nbsp;

Bone County -> Desert Eagles -> **Assault Combat Medic**
For the Assault Combat Medic (MED) we want the ability to heal players. Along with that, we request the following weapons: Desert Eagle, M4, MP5, Combat shotgun, sniper, flash, flowers/heal and parachute.
MED would spawn at the following coordinates: `114.86602020264,2020.052734375,19.268749237061`

---

Lastly we would like to make changes to the following spawn:
Bone County -> Desert Eagles -> **Special Forces**
Namely, we want this spawn to have Double Sawn offs instead of the combat shotgun.

That would be all, thanks in advance.

- Dyam Douglas

**Comment by SAESKain** [comment]
For new spawns you're expected to provide spawn codes.

Re-request this properly.

**Comment by ghost** [comment]
@SAESKain The spawn code for the new medic spawn would be as follows:
`<spawn id="Assault Combat Medic" skin="287,16" x="114.86" y="2020" z="19.268" rot="0" weapons="24,50;27,200;29,1000;31,2000;34,200;17,200;14,1;46,1" description="Assault Combat Medic." r="30" g="130" b="30" restricted="group,demedic"/>`

**Comment by ghost** [comment]
Withdrawn to combine with future changes
