### ISSUE TITLE
Cunning Stunts Spawn Changes

### ISSUE THREAD

**Issue by RealCarter** [saesrpg/saesrpg-group#7]
Hello there,
We would like to remove our public/helper spawn and wanna add Rookie spawn for probationary members instead of it.

Spawn code 
https://pastebin.com/AeS4w54F

Skin shader

Spawn name: Cunning Stunts Rookie
Skin name: wmydrug
Skin id: 29
Model: https://www.mediafire.com/view/n5f1jwdfi9yydze/csskin.png/file

**Comment by IEDaryl** [comment]
Apologies about the delay in response to this request, will review it over the next few days and let you know!

**Comment by IEDaryl** [comment]
Duplicated https://github.com/saesrpg/saesrpg-group/issues/10
