### ISSUE TITLE
IAC Base/spawns changed 

### ISSUE THREAD

**Issue by Dufabo** [saesrpg/saesrpg-group#78]
Greetings,IAC Decided to change base so here we go

Codes for base gates : https://pastebin.com/G8C763F1
Codes for base marker : https://pastebin.com/SV7SMwaZ
Codes for spawns : https://pastebin.com/HpkEutQ4
Base file converted in lua : https://pastebin.com/iuxc9xvm /// https://drive.google.com/open?id=1X5vHaazPRXswpc_9i3V9VizhR6Mx997G

Also we would like to keep current shader of swat skin for the following spawn
["Merryweather"]={
[175]={['fileName']='swat.dds',['textureName']='swat'},
},

**Comment by IEDaryl** [comment]
Request denied as explained in detail on discord re; terrible mapping.
