### ISSUE TITLE
SAPA issues and requests

### ISSUE THREAD

**Issue by tut001** [saesrpg/saesrpg-group#8]
**General issues:**
some people are unable to spawn because of resolution. believe it's Clucking Bell spawn that causes it.
unable to use /voice. 
unable to use /strap. 
unable to use /grab or /heligrab
unable to /helidrop
unable to participate in the VIP event.
unable to arrest people inside locked vehicles.
unable to open the PD doors and the jail red door.

**Requests**
requesting Instructors ability to use /groupsay 
requesting the ability to invite and remove people in cadet group for Instructors.
requesting construction panel for instructors (only with cones will do).
requesting PC and squad spawns ability to open SAPA front gates.
requesting SAPA ins and HQ spawns to have skin `triboss ID 120` changed to skin `tenpen ID 265` 

(optional) requesting a chat for the group e.g /sapa. cmd doesn't really matter.

**Comment by IEDaryl** [comment]
Hello Mr Thor,

Can you confirm which of these issues, if any, are still outstanding?

**Comment by IEDaryl** [comment]
This has exceeded the SLA of 2 days, no response from requester, resolving request.

**Comment by tut001** [comment]
2 days? jesus christ. 

we are currently getting to know what's left to get fixed

**Comment by tut001** [comment]
please re-open

**Comment by tut001** [comment]
ones reported not working:
/strap
sapa gate can't be opened by PC nor squad members
we don't have construction panel
there is no /group chat
