### ISSUE TITLE
Lightning World Sports (LWS) Spawn Changes

### ISSUE THREAD

**Issue by IamYoko** [saesrpg/saesrpg-group#80]
Good day,

To whom it may concern,

The LWS HQ team is requesting a set of changes to our spawn, technically is a minor change to our HR spawn. Please check the spawn code below, if there's any questions or inconvenience please feel free to contact me or any other HQ we will gladly answer your questions.

Besides that, we'd like to request double colts for the spawn, L.W.S. Trusted Member & L.W.S. HR Staff Member.

We look forward to have this updated as soon as you guys can.

Spawn:

>         <class id="Lightning World Sports" r="141" g="182" b="0">
>             <spawn id="L.W.S. Staff Member" skin="189,90,16" x="2308.7" y="2041.6" z="10.82" rot="90" weapons="1,1;14,1;22,200;46,133,150" 
>             description="Staff Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-prob" />
>             <spawn id="L.W.S. Trusted Member" skin="171,172,264" x="2308.7" y="2041.6" z="10.82" rot="90" weapons="1,1;14,1;22,200;31,250;33,500;46,1" 
>             description="Trusted Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-member" />
>             <spawn id="L.W.S. HR Staff Member" skin="294,203,265" x="2308.7" y="2056" z="10.82" rot="90" weapons="1,1;14,1;31,600;33,500;46,1;34,70;22,200" 
>             description="High Ranking Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-highmember" />
>         </class>
> 

Thank you in advance,
Stay safe out there!

**Comment by IEDaryl** [comment]
Dual colts added, changes made, live on next push.
