### ISSUE TITLE
LWS :: Spawn changes / Objects Panel Changes

### ISSUE THREAD

**Issue by IamYoko** [saesrpg/saesrpg-group#82]
Good afternoon lads, 

Here's the changes we'd like to request, as per the previous skin can't be used. Some updates on our spawn codes, feel free to check it yourself.

        <class id="Lightning World Sports" r="141" g="182" b="0">
            <spawn id="L.W.S. Staff Member" skin="16,189,93," x="2308.7" y="2041.6" z="10.82" rot="90" weapons="1,1;14,1;22,200;46,133,150" 
            description="Staff Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-prob" />
            <spawn id="L.W.S. Trusted Member" skin="171,194,264" x="2308.7" y="2041.6" z="10.82" rot="90" weapons="1,1;14,1;22,200;31,250;33,500;46,1" 
            description="Trusted Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-member" />
            <spawn id="L.W.S. HR Staff Member" skin="290,117,203" x="2308.7" y="2056" z="10.82" rot="90" weapons="1,1;14,1;31,600;33,500;46,1;34,70;22,200" 
            description="High Ranking Member of Lightning World Sports." r="141" g="182" b="0" restricted="group,lws-highmember" />
        </class>

We'd like to request shaders for our L.W.S Trusted Member skins:

 L.W.S Trusted Member - [Texture File](https://cdn.discordapp.com/attachments/587548410064666642/699419776769851402/171.dds) - Skin ID: 171 - Texture Name: vwmybjd

 L.W.S Trusted Member - [Texture File](https://cdn.discordapp.com/attachments/587548410064666642/699419777839398992/194.dds) - Skin ID: 194 - Texture Name: crogrl3

 L.W.S Trusted Member - [Texture File](https://cdn.discordapp.com/attachments/587548410064666642/699419775356502116/264.dds) - Skin ID: 264 - Texture Name: wmoice

________________________________________________________________________________________________________

In the last update the only the LWS Staff member spawn received the update for the objects below, while the other two remaining spawns didn't. We want these objects to be uploaded for (LWS HR Staff member) and for (LWS Trusted Member) only.

- Objects are below and checked before by Kain.

	["Dojo wall"] = {2755,0,0,0},
	["Stunt parcour"] = {13647,0,0,0},
	["Wall 5"] = {4724,0,0,0},
	["Pirate Ship"]={8493,0,26.8},
	["Ruin 3"] = {11442,0,0,0},
	["Ruin 1"] = {11440,0,0,0},
	["Pillar 4"] = {3494,0,0,0},
	["Cell gate"] = {2930,0,0,0},
	["Billboard"] = {3337,0,0,0},
	["Statue 3"] = {3471,0,0,0},
	["Carshop sign"] = {10281,0,0,0},
	["Blue Pillar Light"]={3437,0,15.7},

	["Chine"] = {2098,0,0,0},
	["Sports Wall"] = {2395,0,0,0},
	["Bike log"] = {18367,0,0,0},
	["Car Shade Roof"] = {3458,0,0,0},
	["Club Gate"] = {3749,0,0,0},
	["Gate 1"] = {7033,0,0,0},
	["Ring"] = {3438,0,0,0},
	["Wall 6"] = {7921,0,0,0},
	["China Gate"] = {9482,0,0,0},
	["Ruin 8"] = {11426,0,0,0},
	["Tower Hut"] = {11427,0,0,0},
	["Square Garage"] = {8947,0,0,0},
	["Ruin 9"] = {11457,0,0,0},
	["Cabin Log"] = {18259,0,0,0},
	["Ruin Wall"] = {11441,0,0,0},
	["Jetdoor A51"] = {3095,0,0,0},
	["Hot Statue"] = {14467,0,0,0},
	["Pillar 2"] = {3499,0,0,0},
	["Steps"] = {13644,0,0,0},

Thank you in advance.

**Comment by IEDaryl** [comment]
Panel part done by Scorpyo, rest will be reviewed today.

**Comment by IEDaryl** [comment]
Done, live next push.
