### ISSUE TITLE
GXT Changes

### ISSUE THREAD

**Issue by Ramos116** [saesrpg/saesrpg-group#83]
Hello,

our interior wasn't good enough to be in the server, aswell as car lift, so I'm here giving fixed versions:

[base_files.zip](https://github.com/saesrpg/saesrpg-group/files/4434561/base_files.zip)

Next thing: we have GXT Barracks in game, and we can't enter them because we aren't classed as an emergency team, can somebody fix that, so we may do our job.

Another thing: we'd like to change radious of our gate, since daryl had to fix something for us already, he has the last updated code, so he can just change radius for us. ty.

**Comment by Ramos116** [comment]
replace all those 3 files with current ones (exterior file gotta be replaced aswell, because of car lift)

**Comment by jpslimmen2** [comment]
the shader textures we got now are still the same that are applied in game atm so nothing changed there aswell

**Comment by jpslimmen2** [comment]
> 
> 
> Hello,
> 
> our interior wasn't good enough to be in the server, aswell as car lift, so I'm here giving fixed versions:
> 
> [base_files.zip](https://github.com/saesrpg/saesrpg-group/files/4434561/base_files.zip)
> 
> Next thing: we have GXT Barracks in game, and we can't enter them because we aren't classed as an emergency team, can somebody fix that, so we may do our job.
> 
> Another thing: we'd like to change radious of our gate, since daryl had to fix something for us already, he has the last updated code, so he can just change radius for us. ty.

set the trigger to  -1680.39709, 39.90904, 3.55469 and radius to 10

**Comment by Ramos116** [comment]
can we also get access to /cb (truckers radio), ty.

**Comment by IEDaryl** [comment]
> can we also get access to /cb (truckers radio), ty.

Kain added to request for this portion.

**Comment by Ramos116** [comment]
We have also noticed that we cannot see mechanic requests, when someone calls /mech.

Get us access to that as well. Thanks.

**Comment by IEDaryl** [comment]
Done, should be live on next merge and push.
