### ISSUE TITLE
SAPA spawn issues

### ISSUE THREAD

**Issue by tut001** [saesrpg/saesrpg-group#85]
We're missing features:
- able to see 999 p backup calls (red S)
- we cannot use switch or fire weapons around LSPD protection
- we cannot use /strap
- we cannot grab onto vehicles

**Comment by tutgreco** [comment]
Additionally could we place have access to speed trap (/strap)

**Comment by tut001** [comment]
I have compiled the additional issues into the main topic.

**Comment by tut001** [comment]
Thread updated with more issues

**Comment by IEDaryl** [comment]
> We're missing features:
> 
> * cargrab
> * we cannot grab onto vehicles

Are these not the same thing?

> * /barrier

This is a reward locked to ProCops. 

For the rest Kain has been assigned to the ticket.

**Comment by tut001** [comment]
Yes, thanks I've amended it

**Comment by IEDaryl** [comment]
Live next push, thanks to Scorpyo
