### ISSUE TITLE
CC additions

### ISSUE THREAD

**Issue by jaspermta** [saesrpg/saesrpg-group#87]
Hi there,

We've spoken with the Group Management on Discord and our suggestion of having an extra garage was approved, amongst this update we get to keep the garage in SF as well. Thanks a lot for that :)
We finished the project. If there is any issues, hmu here or on DC as you like.

http://www.mediafire.com/folder/12pqd8jqt19l7nh,e73711xp9es2nlr,zlqk4lagzrsulic,y99p9hmmg4b4462,fefahxof5zdzqi3,fakw72pywc6vo9u,9tv6tpu7yk016pz,ucd4kqfn4ztczlh,ggbqky7gjkvgakq,0b3se9sjg7tqelj,7uj7ixnr09gg9qu,78k7sbcfff0pmg0,we80lp2acnr3kwy/shared

In addition, it would be great to see the following things added as well:
- 3 new fuel markers (as the old fuel pump moved into the cc area)
- 1 new refuel marker for Fuel truckers
- 1 Modshop marker in the 24/7 Modshop building alligned to the gas pump

Thanks in advance.

**Comment by IEDaryl** [comment]
Live next push
