### ISSUE TITLE
raceTECH request

### ISSUE THREAD

**Issue by Nuno55** [saesrpg/saesrpg-group#88]
Good evening,

I would like to request an invisible marker to teleport from rT base to the race track (Whenstone track).

Feel free to contact me ingame if you have any question.

raceTECH base marker location:
![image](https://user-images.githubusercontent.com/63817451/79505042-b1040080-802b-11ea-85ad-a59d30aac11f.png)

race track location (1st pit stop near the disk):
![image](https://user-images.githubusercontent.com/63817451/79504887-75693680-802b-11ea-80b0-2c2436665680.png)

Thank you!

**Comment by IEDaryl** [comment]
Done
