### ISSUE TITLE
Cluckin' Bell New Shaders/Script

### ISSUE THREAD

**Issue by locolocoxl** [saesrpg/saesrpg-group#89]
**_Hello there Group Managers, with the help of JohnnyEnglish we've developed a new script which consists in delivering food to bases of gangs/squads and groups (not including special groups) and we also want to change our skins shaders._**

---

**--Spawn Codes--**

`<spawn id="Cluckin' Bell Manager" skin="147,228" x="875.54998" y="1908.47998" z="10.85273" rot="0" weapons="5,1"
description="Cluckin' Bell HQ" r="247" g="187" b="3" restricted="group,cluck-hq"/>`
 
`<spawn id="Cluckin' Bell Supervisor" skin="17,171" x="875.54998" y="1908.47998" z="10.85273" rot="0" weapons="5,1"
description="Cluckin' Bell Supervisor sHQ" r="247" g="187" b="3" restricted=" group,cluck-super"/>`
 
`<spawn id="Cluckin' Bell Employee" skin="171,167" x="875.54998" y="1908.47998" z="10.85273" rot="0" weapons="5,1"
description="Cluckin' Bell Employee" r="247" g="187" b="3" restricted="group,cluck-member"/>`

**--Skins Shaders--**

Download link for shaders: https://www.sendspace.com/file/jc7fla

**--Deliveries Script--**

Download link for deliveries script: https://www.sendspace.com/file/ozkz6k

We'd like to be able to see Store Robberies on the map if it's possible.

**Comment by IEDaryl** [comment]
Outside of the SR visibility (not necessary) and script which is not for GM to review, this is done. Live on next merge and push.
