### ISSUE TITLE
DESERT EAGLES UPDATE - SPAWN CHANGES 

### ISSUE THREAD

**Issue by SAESPatrol** [saesrpg/saesrpg-group#96]
Dear SAESHQ,
We are requesting spawn changes for DE to accommodate for some changes we're trying to work out in the group. 

This topic has been made by both the leader of Desert Eagles SAES>Patrol and his Vice Leader Dyam Douglas, alongside the main base of DE being updated.  

This is a long going project (Project Aurora) to update our spawns since it is been years since they last received an update (airborne, assault, SF), also to accommodate our units to fulfil new RP projects and missions, since DEs activity topic has increased we need to find new methods of making units more appealing depending on what they are aimed for. We work with what we can and we need this. 

### **Skin mods**
New skin mod “army_backpack”, SAES>Tut is in possession of the model named “patrol_smells2”. We would like this skin to replace skin 287 (DE Main skin). Skin shaders are attached in the ZIP file supplied. The shader JSON:
```
["Military Recruit"]={
    [287]={["fileName"]="army_backpack_recruit.dds",["textureName"]="patrol_smells2"},
},

["Assault Unit"]={
    [287]={["fileName"]="army_backpack_assault.dds",["textureName"]="patrol_smells2"},
},

["Assault Combat Medic"]={
    [287]={["fileName"]="army_backpack_assault.dds",["textureName"]="patrol_smells2"},
},

["Naval Unit"]={
    [287]={["fileName"]="army_backpack_navy.dds",["textureName"]="patrol_smells2"},
},

["Naval Airforce Unit"]={
    [287]={["fileName"]="army_backpack_navy.dds",["textureName"]="patrol_smells2"},
},

["Seaman Recruit"]={
    [287]={["fileName"]="army_backpack_recruit.dds",["textureName"]="patrol_smells2"},
},

["Airborne Unit"]={
    [287]={["fileName"]="army_backpack_airborne.dds",["textureName"]="patrol_smells2"},
},

["Special Forces"]={
    [287]={["fileName"]="army_backpack_specops.dds",["textureName"]="patrol_smells2"},
},

["Military Commander"]={
    [287]={["fileName"]="army_backpack_commander.dds",["textureName"]="patrol_smells2"},
},
```

The other skin, “ghillie_suit” mod can replace the unused skin, skin number 235. Skin number 235 is not used by any organization in the server. Files for this skin are also supplied in the ZIP archive. This skin will not receive shaders.

The last skin, “fighter_pilot” mod can replace our General of the Army mod ( officer mod)  skin, skin number 310. Skin number 310. Files for this skin are also supplied in the ZIP archive. This skin will not receive shaders. ( So we would be getting rid of one of our current DEHQs mods and giving it to Airborne Unit) 
IMPORTANT -> 
**SAES>Tut has the lowered versions of the mods, so ask him for the mods  - 
update : tut has sent the mods to nanobob for review**  

We are changing the main skin of DE and removing one of our current DEHQ mods and giving the mod rights to Assault Unit, therefore the only “new” mod would be the ghillie suit. 
------------------------------------------------------------------------------------------------

### Spawn removal

First, we would like to remove a spawn, the spawn we want to be removed is:
Bone County -> Desert Eagles -> Military Cadet (skin 16) 
Military Cadet´s Shader, we want that shader to be removed, and also the skin we will no longer use it.   

### SPAWN UPDATES:

For the changes we want the following spawn to be renamed:

### To: Bone County -> Desert Eagles -> Military Recruit   
We would like this spawn to have the following skins: skin="287". For skin 287 we would like it to have the default shader.

<spawn id="Military Recruit" skin="287" x="102.041015625" y="2022.42578125" z="18.390460968018" rot="0" weapons="24,50;31;1000;34,50" description="Military Recruit Spawn" r="30" g="130" b="30" restricted="group,desert"/> 

### Bone Country -> Desert Eagles -> Assault Unit

We would like this spawn to have the following skins: skin="287,235". 
For skin 287 we would like the “assault” shader supplied for the “patrol_smells2” skin. For skin 235 we don’t require a shader.  (So this spawn would only have the normal DE main Skin and  the Ghillie suit. (2 in total)

<spawn id="Assault Unit" skin="287,235" x="99.013671875" y="1990.1728515625" z="18.428792953491" rot="0" weapons="24,50;27,200;32,5000;31,2000;34,200;39,20;40;16,100" description="The official Assault Unit spawn of DE. " r="30" g="130" b="30" restricted="group,assault"/> 

Changes Applied, we have decided to add C4 and double tec9  to Assault Spawn to properly equip Assault Units (4;39,20) 
 
### Bone Country -> Desert Eagles -> Airborne unit

We would like this spawn to have the following skins: skin="287,310". 
For the skin 287 we would like the “airborne” shader supplied for the “patrol_smells2” skin. For skin 310  we do not require a shader. This spawn would have 2 skins in total : Main DE army guy, and the airborne flight suit (2 in total)

<spawn id="Airborne Unit" skin="287,310" x="281.7841796875" y="1903.6435546875" z="20.228574752808" rot="0" weapons="16,100;24,100;27,200;29,1000;31,2000;34,200" description="The official Air Force spawn of DE. " r="30" g="130" b="30" restricted="group,airborne"/> 

Changes applied, we have decided to remove the flashbang grenades and add fragmentation grenades (16,100)

### Bone Country -> Desert Eagles -> Special Forces

We would like this spawn to have the following skins: skin="287,310,235,311". 
For skin 287 we would like the “special forces” shader supplied for the “patrol_smells2” skin. 
<spawn id="Special Forces" skin="287,310,235,311" x="268.76293945313" y="1800.7606201172" z="11.491149902344" rot="0" weapons="4;24,50;26,500;31,2000;32,5000;34,200;39,200;40;45" description="Special Forces Spawn" r="30" g="130" b="30" restricted="group,specops"/> 

 Changes applied,  added infrared  And double shootgun
 
 
 
### Bone Country -> Desert Eagles -> Military commander

We would like this spawn to have the following skins: skin="287,310,311". 
For skin 287 we would like the “commander” shader supplied for the “patrol_smells2” skin. 

<spawn id="Military Commander" skin="287,310,311" x="214.23046875" y="1865.9541015625" z="13.140625" rot="0" weapons="4; 24,50;27,300;31,2000;32,5000;34,200;39,200;40;45" description="The official spawn of DEHQ members" r="30" g="130" b="30" restricted="group,dehq"/> 

### San Fierro -> Desert Eagles -> Naval Unit / Naval Air Force  Unit / Seaman Recruit (3) 

We would like these spawns to have the following skins: skin="287". 
For skin 287 we would like the “naval” shader supplied for the “patrol_smells2” skin. 

### Bone County -> Desert Eagles -> Assault Combat Medic

For the Assault Combat Medic (MED) we want the ability to heal players. Along with that, we request the following weapons: Desert Eagle, M4, MP5, Combat shotgun, sniper, flash, flowers/heal and parachute.

Assault Combat  Unit would spawn at the following coordinates: 

<spawn id="Assault Combat Medic" skin="287" x="89.1376953125" y="1985.86328125" z="18.000129699707" rot="0" weapons="24,50;27,200;29,1000;31,2000;34,200;17,200;14,1;46,1" description="Assault Combat Medic." r="30" g="130" b="30" restricted="group,demedic"/> 

 ### 
### Bone County -> Desert Eagles ->  Assault K-9 Unit

For the Assault K-9 Unit, we want the dog skin 258. A shader skin for DE-K9  is attached in the zip archive, so the dog looks different from the main police dog. 

Assault K-9 Unit would spawn at the following coordinates: 

<spawn id="Assault K-9 Unit" skin="258" x="85.455078125" y="1977.3984375" z="17.836277008057" rot="0"  description="Assault K-9 Unit spawn" r="30" g="130" b="30" restricted="group,dedog"/> 
 
We have removed the Cadet spawn completely, therefore we would only be adding one new spawn which is the DE Medic one. 

FILES ARE ATTACHED BELOW : 

[DE_Request_attachments.zip](https://github.com/saesrpg/saesrpg-group/files/4678240/DE_Request_attachments.zip)

**Comment by SAESPatrol** [comment]
THESE CHANGES ARE NOT MEANT TO BE APPLIED UNTIL THE NEW BASE IS PUT ON THE LIVE SERVER.

**Comment by SAESPatrol** [comment]
saes>tut has the files of the mod skins  - reminder

**Comment by IEDaryl** [comment]
No response from other ticket, closing.
