### ISSUE TITLE
de base 2.0 request

### ISSUE THREAD

**Issue by SAESPatrol** [saesrpg/saesrpg-group#98]
<trigger x="268.9990234375" y="1888.1572265625" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="group,Military Commander,Special Forces">
    <gate object="11102" pos=" 268.9990234375,1888.1572265625,18.799999237061,0,0,270" start=" 268.9990234375,1888.1572265625,18.799999237061,0,0,270" finish=" 268.9990234375,1888.1572265625,14.431699752808,0,0,270" />
</trigger>
 

 

 
<trigger x="233.599609375" y="1939.5" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="976" pos=" 233.599609375,1939.5,16.60000038147,0,0,180" start=" 233.599609375,1939.5,16.60000038147,0,0,180" finish=" 224.82130432129,1939.5,16.60000038147,0,0,180" />
</trigger>
 

 

 
<trigger x="345.10000610352" y="1797.6999511719" z="18.89999961853" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="989" pos=" 342.79998779297,1796.1999511719,18.700000762939,0,0,322" start=" 342.79998779297,1796.1999511719,18.700000762939,0,0,322" finish=" 342.79998779297,1796.1999511719,15.300000190735,0,0,322" />
</trigger>
 

 

 
<trigger x="345.10000610352" y="1797.6999511719" z="18.89999961853" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="989" pos=" 347.29998779297,1799.3000488281,18.700000762939,0,0,321.498046875" start=" 347.29998779297,1799.3000488281,18.700000762939,0,0,321.498046875" finish=" 347.29998779297,1799.3000488281,15.300000190735,0,0,321.498046875" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="986" pos=" -51.400390625,2061.2998046875,18.200000762939,0,0,90" start=" -51.400390625,2061.2998046875,18.200000762939,0,0,90" finish=" -51.400390625,2055.3208007813,18.200000762939,0,0,90" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="986" pos=" -51.400390625,2069.2001953125,18.200000762939,0,0,90" start=" -51.400390625,2069.2001953125,18.200000762939,0,0,90" finish=" -51.400390625,2075.2814941406,18.200000762939,0,0,90" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2929" pos=" 215.900390625,1875.5,13.89999961853,0,0,0" start=" 215.900390625,1875.5,13.89999961853,0,0,0" finish=" 219.95930480957,1875.5,13,13.89999961853,0,0,0" />
</trigger>
 

 
 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2929" pos=" 211.7998046875,1875.5,13.89999961853,0,0,0" start=" 211.7998046875,1875.5,13.89999961853,0,0,0" finish=" 207.83700561523,1875.5,13,13.89999961853,0,0,0" />
</trigger>
 

 

 
<trigger x="226.5" y="1872.4000244141" z="13.699999809265" height="4.0" radius="8" movetime="2000" allowed="team,public">
    <gate object="2928" pos=" 226.38789367676,1872.427734375,13.983200073242,0,0,90" start=" 226.38789367676,1872.427734375,13.983200073242,0,0,90" finish=" 226.38789367676,1872.427734375,11.39999961853,0,0,90" />
</trigger>
 

 

 
<trigger x="268.81869506836" y="1799.1413574219" z="5.8698000907898" height="4.0" radius="8" movetime="2000" allowed="team,public">
    <gate object="2928" pos=" 268.7822265625,1799.251953125,5.9840998649597,0,0,0" start=" 268.7822265625,1799.251953125,5.9840998649597,0,0,0" finish=" 268.7822265625,1799.251953125,3.5144999027252,0,0,0" />
</trigger>
 

 

 
<trigger x="268.82360839844" y="1798.3227539063" z="12.05449962616" height="4.0" radius="8" movetime="2000" allowed="group,Military Commander,Special Forces">
    <gate object="2930" pos=" 267.94921875,1798.3349609375,13.284600257874,0,0,90" start=" 267.94921875,1798.3349609375,13.284600257874,0,0,90" finish=" 266,1798.3349609375,13.284600257874,0,0,90" />
</trigger>
 

 

 
<trigger x="280.14929199219" y="1788.5330810547" z="-0.74540001153946" height="2.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2930" pos=" 279.33920288086,1788.5808105469,0.62779998779297,0,0,90" start=" 279.33920288086,1788.5808105469,0.62779998779297,0,0,90" finish=" 277.79379272461,1788.6026611328,0.62779998779297,0,0,90" />
</trigger>
 

 

 
<trigger x="281.82800292969" y="1788.4665527344" z="-0.74540001153946" height="2.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2930" pos=" 282.79330444336,1788.5262451172,0.62779998779297,0,0,270" start=" 282.79330444336,1788.5262451172,0.62779998779297,0,0,270" finish=" 284.21490478516,1788.4975585938,0.62779998779297,0,0,270" />
</trigger>
 

 

 
<trigger x="280" y="1824.7001953125" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="968" pos=" 280,1824.7001953125,17.5,0,90,270" start=" 280,1824.7001953125,17.5,0,90,270" finish=" 280,1824.7001953125,17.5,0,358.98333740234,270" />
</trigger>
 

GATES - PASTEBIN  - https://pastebin.com/za3ZqjQc

DE BASE MAP FILE 

https://cdn.discordapp.com/attachments/705131640237588661/715608830536318986/DEBASENEW_1.lua

**Comment by SAESPatrol** [comment]
<trigger x="268.9990234375" y="1888.1572265625" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="group,Military Commander,Special Forces">
    <gate object="11102" pos=" 268.9990234375,1888.1572265625,18.799999237061,0,0,270" start=" 268.9990234375,1888.1572265625,18.799999237061,0,0,270" finish=" 268.9990234375,1888.1572265625,14.431699752808,0,0,270" />
</trigger>
 

 

 
<trigger x="233.599609375" y="1939.5" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="976" pos=" 233.599609375,1939.5,16.60000038147,0,0,180" start=" 233.599609375,1939.5,16.60000038147,0,0,180" finish=" 224.82130432129,1939.5,16.60000038147,0,0,180" />
</trigger>
 

 

 
<trigger x="345.10000610352" y="1797.6999511719" z="18.89999961853" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="989" pos=" 342.79998779297,1796.1999511719,18.700000762939,0,0,322" start=" 342.79998779297,1796.1999511719,18.700000762939,0,0,322" finish=" 342.79998779297,1796.1999511719,15.300000190735,0,0,322" />
</trigger>
 

 

 
<trigger x="345.10000610352" y="1797.6999511719" z="18.89999961853" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="989" pos=" 347.29998779297,1799.3000488281,18.700000762939,0,0,321.498046875" start=" 347.29998779297,1799.3000488281,18.700000762939,0,0,321.498046875" finish=" 347.29998779297,1799.3000488281,15.300000190735,0,0,321.498046875" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="986" pos=" -51.400390625,2061.2998046875,18.200000762939,0,0,90" start=" -51.400390625,2061.2998046875,18.200000762939,0,0,90" finish=" -51.400390625,2055.3208007813,18.200000762939,0,0,90" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="986" pos=" -51.400390625,2069.2001953125,18.200000762939,0,0,90" start=" -51.400390625,2069.2001953125,18.200000762939,0,0,90" finish=" -51.400390625,2075.2814941406,18.200000762939,0,0,90" />
</trigger>
 

 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2929" pos=" 215.900390625,1875.5,13.89999961853,0,0,0" start=" 215.900390625,1875.5,13.89999961853,0,0,0" finish=" 219.95930480957,1875.5,13,13.89999961853,0,0,0" />
</trigger>
 

 
 

 
<trigger x="213.80639648438" y="1875.5290527344" z="13.324199676514" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2929" pos=" 211.7998046875,1875.5,13.89999961853,0,0,0" start=" 211.7998046875,1875.5,13.89999961853,0,0,0" finish=" 207.83700561523,1875.5,13,13.89999961853,0,0,0" />
</trigger>
 

 

 
<trigger x="226.5" y="1872.4000244141" z="13.699999809265" height="4.0" radius="8" movetime="2000" allowed="team,public">
    <gate object="2928" pos=" 226.38789367676,1872.427734375,13.983200073242,0,0,90" start=" 226.38789367676,1872.427734375,13.983200073242,0,0,90" finish=" 226.38789367676,1872.427734375,11.39999961853,0,0,90" />
</trigger>
 

 

 
<trigger x="268.81869506836" y="1799.1413574219" z="5.8698000907898" height="4.0" radius="8" movetime="2000" allowed="team,public">
    <gate object="2928" pos=" 268.7822265625,1799.251953125,5.9840998649597,0,0,0" start=" 268.7822265625,1799.251953125,5.9840998649597,0,0,0" finish=" 268.7822265625,1799.251953125,3.5144999027252,0,0,0" />
</trigger>
 

 

 
<trigger x="268.82360839844" y="1798.3227539063" z="12.05449962616" height="4.0" radius="8" movetime="2000" allowed="group,Military Commander,Special Forces">
    <gate object="2930" pos=" 267.94921875,1798.3349609375,13.284600257874,0,0,90" start=" 267.94921875,1798.3349609375,13.284600257874,0,0,90" finish=" 266,1798.3349609375,13.284600257874,0,0,90" />
</trigger>
 

 

 
<trigger x="280.14929199219" y="1788.5330810547" z="-0.74540001153946" height="2.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2930" pos=" 279.33920288086,1788.5808105469,0.62779998779297,0,0,90" start=" 279.33920288086,1788.5808105469,0.62779998779297,0,0,90" finish=" 277.79379272461,1788.6026611328,0.62779998779297,0,0,90" />
</trigger>
 

 

 
<trigger x="281.82800292969" y="1788.4665527344" z="-0.74540001153946" height="2.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="2930" pos=" 282.79330444336,1788.5262451172,0.62779998779297,0,0,270" start=" 282.79330444336,1788.5262451172,0.62779998779297,0,0,270" finish=" 284.21490478516,1788.4975585938,0.62779998779297,0,0,270" />
</trigger>
 

 

 
<trigger x="280" y="1824.7001953125" z="17.28989982605" height="4.0" radius="8" movetime="2000" allowed="team,Desert Eagles">
    <gate object="968" pos=" 280,1824.7001953125,17.5,0,90,270" start=" 280,1824.7001953125,17.5,0,90,270" finish=" 280,1824.7001953125,17.5,0,358.98333740234,270" />
</trigger>

**Comment by tpjham** [comment]
Mapping is horrible, redo it in a more fitting way for a military base

**Comment by tombaath** [comment]
Mapping looks horrible, redo it in a way that is more fitting for a military base.

**Comment by IEDaryl** [comment]
No response, closing.
